/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegislaturasRouteImport } from './routes/legislaturas'
import { Route as IndexRouteImport } from './routes/index'

const LegislaturasRoute = LegislaturasRouteImport.update({
  id: '/legislaturas',
  path: '/legislaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legislaturas': typeof LegislaturasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legislaturas': typeof LegislaturasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legislaturas': typeof LegislaturasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/legislaturas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/legislaturas'
  id: '__root__' | '/' | '/legislaturas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegislaturasRoute: typeof LegislaturasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legislaturas': {
      id: '/legislaturas'
      path: '/legislaturas'
      fullPath: '/legislaturas'
      preLoaderRoute: typeof LegislaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegislaturasRoute: LegislaturasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
