/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeputadosRouteImport } from './routes/deputados'
import { Route as IndexRouteImport } from './routes/index'

const DeputadosRoute = DeputadosRouteImport.update({
  id: '/deputados',
  path: '/deputados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deputados': typeof DeputadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deputados': typeof DeputadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deputados': typeof DeputadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deputados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deputados'
  id: '__root__' | '/' | '/deputados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeputadosRoute: typeof DeputadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deputados': {
      id: '/deputados'
      path: '/deputados'
      fullPath: '/deputados'
      preLoaderRoute: typeof DeputadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeputadosRoute: DeputadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
